k9s:
  cluster: luccakube-local-lauzuret
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - all
    - default
  view:
    active: application
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
