plugins:
  arc_copy_url:
    shortCut: Shift-C
    scopes:
      - ephemeralrunners
    description: |
      Copy workflow url
    confirm: false
    dangerous: false
    command: sh
    background: true
    args:
      - -c
      - |
        kubectl get $RESOURCE_NAME $NAME -n $NAMESPACE -o json | jq -r '"https://github.com/\(.status.jobRepositoryName)/actions/runs/\(.status.workflowRunId)"' | pbcopy
  remove_finalizers:
    shortCut: Ctrl-F
    confirm: true
    dangerous: true
    scopes:
      - all
    description: |
      finalizers
    command: kubectl
    background: true
    args:
      - patch
      - --context
      - $CONTEXT
      - --namespace
      - $NAMESPACE
      - $RESOURCE_NAME.$RESOURCE_GROUP
      - $NAME
      - -p
      - '{"metadata":{"finalizers":null}}'
      - --type
      - merge
